services:
  wireguard:
    image: your-wireguard-demo:latest
    build: .
    ports:
      - '44444:51111/udp'
    cap_add:
      - NET_ADMIN # Needed to run iptables commands, otherwise: error: "iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)"
